# Generated by Django 2.2.4 on 2019-08-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
