# Generated by Django 2.2.4 on 2019-08-16 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20190814_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='htm',
            field=models.CharField(default=datetime.datetime(2019, 8, 16, 11, 21, 25, 936931, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
