# Generated by Django 2.2.4 on 2019-08-16 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_destination_htm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='htm',
        ),
        migrations.AddField(
            model_name='destination',
            name='html',
            field=models.CharField(default=datetime.datetime(2019, 8, 16, 11, 22, 15, 906443, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
